version: "3"

services:  
  frontend:
    container_name: kitt4sme-digital-datasheets-frontend
    image: ryankford/digital-datasheets:1.0-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - internal-network  
    depends_on:
      - backend

networks:
    internal-network:
      driver: bridge
