apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/
    frontend/frontend-service.yaml
    frontend/frontend-deployment.yaml
    frontend/internal-network-networkpolicy.yaml
  - backend/
  - database/