apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- frontend/frontend-deployment.yaml 
- frontend/frontend-service.yaml 
- frontend/frontend-networkpolicy.yaml 
- backend/backend-deployment.yaml 
- backend/backend-service.yaml 
- backend/backend-networkpolicy.yaml 
- database/database-deployment.yaml 
- database/database-service.yaml 
- database/database-networkpolicy.yaml