apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/
  - backend/
  - database/

digital-datasheets/
  frontend/
    frontend/frontend-service.yaml
    frontend/frontend-deployment.yaml
    frontend/internal-network-networkpolicy.yaml
  backend/
    backend/backend-service.yaml
    backend/backend-deployment.yaml
    backend/internal-network-networkpolicy.yaml
  datasbase/
    datasbase/datasbase-service.yaml
    datasbase/datasbase-deployment.yaml
    datasbase/internal-network-networkpolicy.yaml