version: "3.8"

services:

  backend:
    container_name: kitt4sme-digital-datasheets-backend
    image: ryankford/digital-datasheets:1.0-backend
    build: .
    ports:
      - '5000:5000'
    environment:
      - MYSQL_DATABASE=db_KITT
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=kitt4sme-digital-datasheets-database
      - MYSQL_PORT=3306
    networks:
      - internal-network    
    depends_on:
      - database

networks:
    internal-network:
      driver: bridge